language: python
sudo: false
addons:
  apt:
    packages:
    - libopencv-dev
python:
  - "2.7"
before_install:
  - pip install -U pip
  - pip install wheel
install:
  - "pip wheel -r requirements-dev.txt"
  - "pip install -r requirements-dev.txt"
script:
  - py.test
